# Generated by Django 6.0.3 on 2026-06-28 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_role_can_manage_news'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. The announcement will automatically hide after this date and time.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('target_branch', models.ForeignKey(blank=True, help_text='Leave blank to show to all branches.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.branch')),
                ('target_department', models.ForeignKey(blank=True, help_text='Leave blank to show to all departments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
