# Generated by Django 6.0.3 on 2026-07-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='target_department',
        ),
    ]
