# Generated by Django 6.0.3 on 2026-03-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_unique_active_email_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_access_dashboard',
            field=models.BooleanField(default=False, verbose_name='Access Dashboard'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_access_settings',
            field=models.BooleanField(default=False, verbose_name='Access Settings'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_create_ticket',
            field=models.BooleanField(default=True, verbose_name='Create Ticket'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_message',
            field=models.BooleanField(default=False, verbose_name='Delete Message'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_edit_message',
            field=models.BooleanField(default=False, verbose_name='Edit Message'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_pick_ticket',
            field=models.BooleanField(default=False, verbose_name='Pick Ticket'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_send_message',
            field=models.BooleanField(default=True, verbose_name='Send Message'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_update_closed_ticket',
            field=models.BooleanField(default=False, verbose_name='Update Status after closed'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_update_status',
            field=models.BooleanField(default=False, verbose_name='Update Ticket Status'),
        ),
    ]
