# Generated by Django 6.0.3 on 2026-03-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_role_can_access_dashboard_role_can_access_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_create_branch',
            field=models.BooleanField(default=False, verbose_name='Create Branch'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_create_category',
            field=models.BooleanField(default=False, verbose_name='Create Category'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_create_department',
            field=models.BooleanField(default=False, verbose_name='Create Department'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_create_role',
            field=models.BooleanField(default=False, verbose_name='Create Role'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_create_user',
            field=models.BooleanField(default=False, verbose_name='Create User'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_branch',
            field=models.BooleanField(default=False, verbose_name='Delete Branch'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_category',
            field=models.BooleanField(default=False, verbose_name='Delete Category'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_department',
            field=models.BooleanField(default=False, verbose_name='Delete Department'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_role',
            field=models.BooleanField(default=False, verbose_name='Delete Role'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_user',
            field=models.BooleanField(default=False, verbose_name='Delete User'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_email',
            field=models.BooleanField(default=False, verbose_name='Manage Email Settings'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_update_branch',
            field=models.BooleanField(default=False, verbose_name='Edit Branch'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_update_category',
            field=models.BooleanField(default=False, verbose_name='Edit Category'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_update_department',
            field=models.BooleanField(default=False, verbose_name='Edit Department'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_update_role',
            field=models.BooleanField(default=False, verbose_name='Edit Role'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_update_user',
            field=models.BooleanField(default=False, verbose_name='Edit User'),
        ),
    ]
