# Generated by Django 6.0.3 on 2026-03-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_role_can_create_branch_role_can_create_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_update_ticket',
            field=models.BooleanField(default=False, verbose_name='Edit Ticket'),
        ),
    ]
