# Generated by Django 6.0.3 on 2026-06-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_role_can_update_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
    ]
