# Generated by Django 6.0.3 on 2026-06-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_default_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_news',
            field=models.BooleanField(default=False, verbose_name='Manage News'),
        ),
    ]
