# Generated by Django 6.0.3 on 2026-06-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_role_can_manage_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_view_leaderboard',
            field=models.BooleanField(default=False, verbose_name='View Agent Leaderboard'),
        ),
    ]
