# Generated by Django 6.0.3 on 2026-07-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_role_can_view_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_access_kb',
            field=models.BooleanField(default=False, verbose_name='Access Knowledge Base'),
        ),
    ]
