# Generated by Django 6.0.3 on 2026-07-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_role_can_access_kb'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_kb',
            field=models.BooleanField(default=False, verbose_name='Manage Knowledge Base'),
        ),
    ]
