# Generated by Django 6.0.3 on 2026-07-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_role_can_manage_kb'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_maintenance',
            field=models.BooleanField(default=False, verbose_name='Manage System Maintenance'),
        ),
    ]
