# Generated by Django 6.0.3 on 2026-07-25 11:41

from django.db import migrations, models


def seed_email_format(apps, schema_editor):
    # Historical no-op: these models were later removed in 0016.
    # Kept so fresh installs do not depend on deleted app modules.
    pass


def unseed_email_format(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_emailsetting_notify_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(default='mlamehticket', max_length=100)),
                ('accent_color', models.CharField(default='#4f46e5', max_length=7)),
                ('footer_note', models.TextField(default='You’re receiving this because email notifications are enabled for your mlamehticket account.')),
            ],
            options={
                'verbose_name': 'Email Appearance',
                'verbose_name_plural': 'Email Appearance',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('new_ticket', 'New ticket'), ('ticket_picked', 'Ticket picked'), ('ticket_message', 'Ticket message'), ('ticket_status', 'Status change'), ('ticket_update', 'Ticket update'), ('transfer_requested', 'Transfer requested'), ('transfer_accepted', 'Transfer accepted'), ('transfer_denied', 'Transfer declined'), ('announcement', 'Announcement')], max_length=40, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=255)),
                ('intro', models.TextField(blank=True)),
                ('message_title', models.CharField(blank=True, max_length=100)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='When off, built-in default copy is used instead.')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['event_type'],
            },
        ),
        migrations.RunPython(seed_email_format, unseed_email_format),
    ]
