# Generated by Django 6.0.3 on 2026-07-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_email_appearance_and_templates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailAppearance',
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
