# Generated by Django 6.0.3 on 2026-07-25 12:37

from django.db import migrations, models


def seed_email_designer(apps, schema_editor):
    from notifications.email_messages import (
        DEFAULT_ACCENT_COLOR,
        DEFAULT_BRAND_NAME,
        DEFAULT_EMAIL_MESSAGES,
        DEFAULT_FOOTER_NOTE,
    )

    EmailBrand = apps.get_model("core", "EmailBrand")
    EmailMessage = apps.get_model("core", "EmailMessage")

    if not EmailBrand.objects.filter(pk=1).exists():
        EmailBrand.objects.create(
            pk=1,
            brand_name=DEFAULT_BRAND_NAME,
            accent_color=DEFAULT_ACCENT_COLOR,
            footer_note=DEFAULT_FOOTER_NOTE,
        )

    for event_type, fields in DEFAULT_EMAIL_MESSAGES.items():
        EmailMessage.objects.get_or_create(
            event_type=event_type,
            defaults={
                "subject": fields["subject"],
                "title": fields["title"],
                "opening": fields["opening"],
                "message_label": fields["message_label"],
                "button_label": fields["button_label"],
            },
        )


def unseed_email_designer(apps, schema_editor):
    EmailBrand = apps.get_model("core", "EmailBrand")
    EmailMessage = apps.get_model("core", "EmailMessage")
    EmailMessage.objects.all().delete()
    EmailBrand.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_email_appearance_and_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(default='mlamehticket', max_length=100)),
                ('accent_color', models.CharField(default='#4f46e5', max_length=7)),
                ('footer_note', models.TextField(default='You’re receiving this because email notifications are enabled for your mlamehticket account.')),
            ],
            options={
                'verbose_name': 'Email Brand',
                'verbose_name_plural': 'Email Brand',
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('new_ticket', 'New ticket'), ('ticket_picked', 'Ticket picked'), ('ticket_message', 'Reply'), ('ticket_status', 'Status change'), ('ticket_update', 'Ticket update'), ('transfer_requested', 'Transfer requested'), ('transfer_accepted', 'Transfer accepted'), ('transfer_denied', 'Transfer declined'), ('announcement', 'Announcement')], max_length=40, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('opening', models.TextField(blank=True)),
                ('message_label', models.CharField(blank=True, max_length=100)),
                ('button_label', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
                'ordering': ['event_type'],
            },
        ),
        migrations.RunPython(seed_email_designer, unseed_email_designer),
    ]
