# Generated by Django 6.0.3 on 2026-07-25 12:37

from django.db import migrations, models


def seed_email_designer(apps, schema_editor):
    # Inline defaults so this migration does not depend on app code removed later.
    default_messages = {
        "new_ticket": {
            "subject": "[{{ brand_name }}] New ticket #{{ ticket_number }}: {{ ticket_title }}",
            "title": "New ticket #{{ ticket_number }}",
            "opening": "{{ actor_name }} submitted a new request{{ department_suffix }}.",
            "message_label": "Request",
            "button_label": "View ticket",
        },
        "ticket_picked": {
            "subject": "[{{ brand_name }}] Ticket #{{ ticket_number }} picked up",
            "title": "Ticket #{{ ticket_number }} was picked up",
            "opening": "{{ actor_name }} is now handling this ticket. Status is {{ status }}.",
            "message_label": "Request",
            "button_label": "View ticket",
        },
        "ticket_message": {
            "subject": "[{{ brand_name }}] New reply on #{{ ticket_number }}",
            "title": "New reply on #{{ ticket_number }}",
            "opening": "{{ actor_name }} replied to this ticket.",
            "message_label": "Message",
            "button_label": "View conversation",
        },
        "ticket_status": {
            "subject": "[{{ brand_name }}] Status update on #{{ ticket_number }}: {{ status }}",
            "title": "Status changed on #{{ ticket_number }}",
            "opening": "{{ actor_name }} updated the status to {{ status }}.",
            "message_label": "Request",
            "button_label": "View ticket",
        },
        "ticket_update": {
            "subject": "[{{ brand_name }}] Update on ticket #{{ ticket_number }}",
            "title": "Ticket #{{ ticket_number }} was updated",
            "opening": "{{ actor_name }} updated this ticket.",
            "message_label": "Update",
            "button_label": "View ticket",
        },
        "transfer_requested": {
            "subject": "[{{ brand_name }}] Transfer requested: #{{ ticket_number }}",
            "title": "Transfer requested for #{{ ticket_number }}",
            "opening": "{{ actor_name }} requested a department transfer.",
            "message_label": "Request",
            "button_label": "Review transfer",
        },
        "transfer_accepted": {
            "subject": "[{{ brand_name }}] Transfer accepted: #{{ ticket_number }}",
            "title": "Transfer accepted for #{{ ticket_number }}",
            "opening": "{{ actor_name }} accepted the transfer request.",
            "message_label": "Request",
            "button_label": "View ticket",
        },
        "transfer_denied": {
            "subject": "[{{ brand_name }}] Transfer declined: #{{ ticket_number }}",
            "title": "Transfer declined for #{{ ticket_number }}",
            "opening": "{{ actor_name }} declined the transfer request.",
            "message_label": "Request",
            "button_label": "View ticket",
        },
        "announcement": {
            "subject": "[{{ brand_name }}] Announcement: {{ announcement_title }}",
            "title": "{{ announcement_title }}",
            "opening": "A new announcement has been posted in {{ brand_name }}.",
            "message_label": "Announcement",
            "button_label": "View announcements",
        },
    }

    EmailBrand = apps.get_model("core", "EmailBrand")
    EmailMessage = apps.get_model("core", "EmailMessage")

    if not EmailBrand.objects.filter(pk=1).exists():
        EmailBrand.objects.create(
            pk=1,
            brand_name="mlamehticket",
            accent_color="#4f46e5",
            footer_note=(
                "You’re receiving this because email notifications are enabled "
                "for your mlamehticket account."
            ),
        )

    for event_type, fields in default_messages.items():
        EmailMessage.objects.get_or_create(
            event_type=event_type,
            defaults={
                "subject": fields["subject"],
                "title": fields["title"],
                "opening": fields["opening"],
                "message_label": fields["message_label"],
                "button_label": fields["button_label"],
            },
        )


def unseed_email_designer(apps, schema_editor):
    EmailBrand = apps.get_model("core", "EmailBrand")
    EmailMessage = apps.get_model("core", "EmailMessage")
    EmailMessage.objects.all().delete()
    EmailBrand.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_email_appearance_and_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(default='mlamehticket', max_length=100)),
                ('accent_color', models.CharField(default='#4f46e5', max_length=7)),
                ('footer_note', models.TextField(default='You’re receiving this because email notifications are enabled for your mlamehticket account.')),
            ],
            options={
                'verbose_name': 'Email Brand',
                'verbose_name_plural': 'Email Brand',
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('new_ticket', 'New ticket'), ('ticket_picked', 'Ticket picked'), ('ticket_message', 'Reply'), ('ticket_status', 'Status change'), ('ticket_update', 'Ticket update'), ('transfer_requested', 'Transfer requested'), ('transfer_accepted', 'Transfer accepted'), ('transfer_denied', 'Transfer declined'), ('announcement', 'Announcement')], max_length=40, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('opening', models.TextField(blank=True)),
                ('message_label', models.CharField(blank=True, max_length=100)),
                ('button_label', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
                'ordering': ['event_type'],
            },
        ),
        migrations.RunPython(seed_email_designer, unseed_email_designer),
    ]
