# Generated by Django 6.0.3 on 2026-07-28 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_emailtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['department__name', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='emailsetting',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Email Setting', 'verbose_name_plural': 'Email Settings'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='default_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Default Priority'),
        ),
        migrations.AlterField(
            model_name='category',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='emailsetting',
            name='encryption',
            field=models.CharField(choices=[('none', 'None'), ('tls', 'TLS'), ('ssl', 'SSL')], default='tls', max_length=10, verbose_name='Encryption'),
        ),
        migrations.AlterField(
            model_name='emailsetting',
            name='from_email',
            field=models.EmailField(max_length=254, verbose_name='From Email'),
        ),
        migrations.AlterField(
            model_name='emailsetting',
            name='from_name',
            field=models.CharField(max_length=255, verbose_name='From Name'),
        ),
        migrations.AlterField(
            model_name='emailsetting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='emailsetting',
            name='smtp_email',
            field=models.EmailField(max_length=254, verbose_name='SMTP Email'),
        ),
        migrations.AlterField(
            model_name='emailsetting',
            name='smtp_host',
            field=models.CharField(max_length=255, verbose_name='SMTP Host'),
        ),
        migrations.AlterField(
            model_name='emailsetting',
            name='smtp_password',
            field=models.CharField(max_length=255, verbose_name='SMTP Password'),
        ),
        migrations.AlterField(
            model_name='emailsetting',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, verbose_name='SMTP Port'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
