# Generated by Django 6.0.3 on 2026-03-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('branch', 'Needs Support'), ('support', 'Support Agent')], default='branch', max_length=20),
        ),
    ]
