# Generated by Django 6.0.3 on 2026-06-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_normalize_email_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
