# Generated by Django 6.0.3 on 2026-07-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_i18n_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='requires_password_change',
            field=models.BooleanField(default=False, verbose_name='Requires password change'),
        ),
    ]
