<#
    envfile.ps1 - Generate or merge a production .env for mlamehticket.
#>

$script:WindowsToIana = @{
    "Arab Standard Time"           = "Asia/Riyadh"
    "Arabic Standard Time"         = "Asia/Baghdad"
    "Egypt Standard Time"          = "Africa/Cairo"
    "GMT Standard Time"            = "Europe/London"
    "Greenwich Standard Time"      = "Atlantic/Reykjavik"
    "UTC"                          = "UTC"
    "Pacific Standard Time"        = "America/Los_Angeles"
    "Mountain Standard Time"       = "America/Denver"
    "Central Standard Time"        = "America/Chicago"
    "Eastern Standard Time"        = "America/New_York"
    "W. Europe Standard Time"      = "Europe/Berlin"
    "Central Europe Standard Time" = "Europe/Budapest"
    "Romance Standard Time"        = "Europe/Paris"
    "Turkey Standard Time"         = "Europe/Istanbul"
    "Russian Standard Time"        = "Europe/Moscow"
    "India Standard Time"          = "Asia/Kolkata"
    "China Standard Time"          = "Asia/Shanghai"
    "Tokyo Standard Time"          = "Asia/Tokyo"
    "AUS Eastern Standard Time"    = "Australia/Sydney"
    "South Africa Standard Time"   = "Africa/Johannesburg"
}

function Get-IanaTimeZone {
    try {
        $winId = (Get-TimeZone).Id
        if ($script:WindowsToIana.ContainsKey($winId)) {
            return $script:WindowsToIana[$winId]
        }
    }
    catch { }
    return "UTC"
}

function New-UrlSafeSecret {
    param([int]$ByteLength = 48)
    $bytes = New-Object byte[] $ByteLength
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return [Convert]::ToBase64String($bytes).TrimEnd("=").Replace("+", "-").Replace("/", "_")
}

function Write-EnvFile {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][hashtable]$Values
    )
    $lines = @(
        "# Generated by mlamehticket installer - do not commit",
        "DEBUG=$($Values.DEBUG)",
        "SECRET_KEY=$($Values.SECRET_KEY)",
        "ALLOWED_HOSTS=$($Values.ALLOWED_HOSTS)",
        "CSRF_TRUSTED_ORIGINS=$($Values.CSRF_TRUSTED_ORIGINS)",
        "SITE_URL=$($Values.SITE_URL)",
        "",
        "DB_ENGINE=$($Values.DB_ENGINE)",
        "DB_NAME=$($Values.DB_NAME)",
        "DB_USER=$($Values.DB_USER)",
        "DB_PASSWORD=$($Values.DB_PASSWORD)",
        "DB_HOST=$($Values.DB_HOST)",
        "DB_PORT=$($Values.DB_PORT)",
        "",
        "DEFAULT_SUPERADMIN_USERNAME=$($Values.DEFAULT_SUPERADMIN_USERNAME)",
        "DEFAULT_SUPERADMIN_EMAIL=$($Values.DEFAULT_SUPERADMIN_EMAIL)",
        "DEFAULT_SUPERADMIN_PASSWORD=$($Values.DEFAULT_SUPERADMIN_PASSWORD)",
        "",
        "BACKUP_DIR=$($Values.BACKUP_DIR)",
        "BACKUP_KEEP=$($Values.BACKUP_KEEP)",
        "TIME_ZONE=$($Values.TIME_ZONE)",
        "LOG_LEVEL=$($Values.LOG_LEVEL)",
        "LOG_TO_FILE=$($Values.LOG_TO_FILE)"
    )
    Set-Content -Path $Path -Value ($lines -join "`r`n") -Encoding UTF8
}

function New-ProductionEnv {
    param(
        [Parameter(Mandatory)][string]$InstallDir,
        [Parameter(Mandatory)][string]$ServerAddress,
        [Parameter(Mandatory)][int]$Port,
        [Parameter(Mandatory)][string]$AdminEmail,
        [string]$DbName = "mlamehticket",
        [string]$DbUser = "mlamehticket_user",
        [string]$DbPassword = "",
        [string]$AdminPassword = ""
    )

    if ([string]::IsNullOrWhiteSpace($DbName)) { $DbName = "mlamehticket" }
    if ([string]::IsNullOrWhiteSpace($DbUser)) { $DbUser = "mlamehticket_user" }
    if ([string]::IsNullOrWhiteSpace($DbPassword)) {
        $DbPassword = New-SecurePassword -Length 28
    }
    if ([string]::IsNullOrWhiteSpace($AdminPassword)) {
        $AdminPassword = New-SecurePassword -Length 20
    }

    $siteUrl = "http://${ServerAddress}:${Port}"
    $values = @{
        DEBUG                         = "0"
        SECRET_KEY                    = (New-UrlSafeSecret)
        ALLOWED_HOSTS                 = "localhost,127.0.0.1,$ServerAddress"
        CSRF_TRUSTED_ORIGINS          = $siteUrl
        SITE_URL                      = $siteUrl
        DB_ENGINE                     = "mysql"
        DB_NAME                       = $DbName
        DB_USER                       = $DbUser
        DB_PASSWORD                   = $DbPassword
        DB_HOST                       = "localhost"
        DB_PORT                       = "3306"
        DEFAULT_SUPERADMIN_USERNAME   = "admin"
        DEFAULT_SUPERADMIN_EMAIL      = $AdminEmail
        DEFAULT_SUPERADMIN_PASSWORD   = $AdminPassword
        BACKUP_DIR                    = "./backups"
        BACKUP_KEEP                   = "14"
        TIME_ZONE                     = (Get-IanaTimeZone)
        LOG_LEVEL                     = "INFO"
        LOG_TO_FILE                   = "1"
    }

    $envPath = Join-Path $InstallDir ".env"
    Write-EnvFile -Path $envPath -Values $values
    Write-InstallStep "Wrote production .env"
    return $values
}

function Merge-EnvFromExample {
    param(
        [Parameter(Mandatory)][string]$InstallDir,
        [string]$PackageVersion = ""
    )
    $envPath = Join-Path $InstallDir ".env"
    $example = Join-Path $InstallDir ".env.example"
    if (-not (Test-Path $envPath)) {
        throw ".env missing during repair/upgrade - cannot merge. Reinstall as fresh or restore .env from backup."
    }
    if (-not (Test-Path $example)) {
        Write-InstallWarn ".env.example missing; skipping key merge."
        return
    }

    $existingKeys = @{}
    foreach ($line in Get-Content $envPath) {
        if ($line -match "^\s*#") { continue }
        if ($line -match "^\s*([^=]+)\s*=") {
            $existingKeys[$matches[1].Trim()] = $true
        }
    }

    $toAppend = @()
    foreach ($line in Get-Content $example) {
        if ($line -match "^\s*#") { continue }
        if ($line -match "^\s*$") { continue }
        if ($line -match "^\s*([^=]+)\s*=\s*(.*)$") {
            $key = $matches[1].Trim()
            $val = $matches[2].Trim()
            if (-not $existingKeys.ContainsKey($key)) {
                if ($toAppend.Count -eq 0) {
                    $toAppend += ""
                    $comment = if ($PackageVersion) { "# Added by upgrade to $PackageVersion" } else { "# Added by installer merge" }
                    $toAppend += $comment
                }
                $toAppend += "$key=$val"
                Write-InstallStep "Appending new .env key: $key"
            }
        }
    }

    if ($toAppend.Count -gt 0) {
        Add-Content -Path $envPath -Value ($toAppend -join "`r`n") -Encoding UTF8
    }
    else {
        Write-InstallStep "No new .env keys to merge."
    }
}

function Write-FirstLoginFile {
    param(
        [Parameter(Mandatory)][string]$InstallDir,
        [Parameter(Mandatory)][hashtable]$EnvValues,
        [string]$MySqlRootPassword = "",
        [switch]$WeInstalledMySql
    )
    $path = Join-Path $InstallDir "FIRST-LOGIN.txt"
    $lines = @(
        "mlamehticket - first login credentials",
        "======================================",
        "",
        "Open: $($EnvValues.SITE_URL)",
        "",
        "Admin username: $($EnvValues.DEFAULT_SUPERADMIN_USERNAME)",
        "Admin password: $($EnvValues.DEFAULT_SUPERADMIN_PASSWORD)",
        "Admin email:    $($EnvValues.DEFAULT_SUPERADMIN_EMAIL)",
        "",
        "You will be required to change the admin password on first login.",
        "",
        "Database:",
        "  Host: $($EnvValues.DB_HOST):$($EnvValues.DB_PORT)",
        "  Name: $($EnvValues.DB_NAME)",
        "  User: $($EnvValues.DB_USER)",
        "  Password: $($EnvValues.DB_PASSWORD)"
    )
    if ($WeInstalledMySql -and $MySqlRootPassword) {
        $lines += ""
        $lines += "MySQL root password (bundled server only): $MySqlRootPassword"
        $lines += "Keep this private. The application uses mlamehticket_user, not root."
    }
    $lines += ""
    $lines += "This file is restricted to Administrators. Store credentials securely and delete this file when done."
    Set-Content -Path $path -Value ($lines -join "`r`n") -Encoding UTF8
    Restrict-AclToAdministrators -Path $path
    Write-InstallStep "Wrote FIRST-LOGIN.txt"
    return $path
}
