# Generated by Django 6.0.3 on 2026-10-06 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_requires_password_change_verbose'),
        ('core', '0023_role_can_manage_shifts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('is_night', models.BooleanField(default=False, editable=False, verbose_name='Night')),
                ('colour', models.CharField(default='#6366f1', max_length=7, verbose_name='Colour')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_types', to='core.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Shift type',
                'verbose_name_plural': 'Shift types',
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time_override', models.TimeField(blank=True, null=True, verbose_name='Start override')),
                ('end_time_override', models.TimeField(blank=True, null=True, verbose_name='End override')),
                ('times_set_at', models.DateTimeField(blank=True, null=True, verbose_name='Times set at')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Checked in at')),
                ('times_set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_times_set', to=settings.AUTH_USER_MODEL, verbose_name='Times set by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='shifts.shifttype', verbose_name='Shift type')),
            ],
            options={
                'verbose_name': 'Shift assignment',
                'verbose_name_plural': 'Shift assignments',
                'ordering': ['date', 'user_id'],
            },
        ),
        migrations.AddIndex(
            model_name='shifttype',
            index=models.Index(fields=['department', 'archived'], name='shifts_shif_departm_2d9ac1_idx'),
        ),
        migrations.AddConstraint(
            model_name='shifttype',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='uniq_shift_type_department_name'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['date'], name='shifts_shif_date_308f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['shift_type', 'date'], name='shifts_shif_shift_t_af3f28_idx'),
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uniq_shift_assignment_user_date'),
        ),
    ]
