# Generated by Django 6.0.3 on 2026-10-06 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttype',
            name='colour',
            field=models.CharField(default='#6366f1', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')], verbose_name='Colour'),
        ),
    ]
