# Generated by Django 6.0.3 on 2026-07-01 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
        ('tickets', '0011_ticketstatushistory_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_ticket',
            field=models.ForeignKey(blank=True, help_text='Ticket that inspired or is resolved by this article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_articles', to='tickets.ticket'),
        ),
    ]
