# Generated by Django 6.0.3 on 2026-07-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_article_related_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('document', 'Document (Default)'), ('book', 'Book'), ('wrench', 'Wrench'), ('shield', 'Shield'), ('star', 'Star'), ('info', 'Info'), ('users', 'Users'), ('help', 'Help'), ('globe', 'Globe')], default='document', help_text='Icon to display for this category', max_length=50),
        ),
    ]
