# Generated by Django 6.0.3 on 2026-09-30 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_category_icon'),
        ('tickets', '0013_performance_hotpaths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published', '-updated_at'], name='kb_pub_updated_idx'),
        ),
    ]
