# Generated by Django 6.0.3 on 2026-10-03 12:04

from django.db import migrations, models


def published_articles_visible_to_all_support(apps, schema_editor):
    Article = apps.get_model("kb", "Article")
    Article.objects.filter(is_published=True).update(visibility="all_support")


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_shell_pane_list_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visibility',
            field=models.CharField(choices=[('only_me', 'Only me'), ('department', 'My department'), ('all_support', 'All support')], default='all_support', help_text='Who can read this article after it is published.', max_length=20),
        ),
        migrations.RunPython(
            published_articles_visible_to_all_support,
            migrations.RunPython.noop,
        ),
    ]
