# Generated by Django 6.0.3 on 2026-10-03 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_i18n_verbose_names'),
        ('kb', '0005_article_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visibility_department',
            field=models.ForeignKey(blank=True, help_text="Author's department at the time this article was published to that department.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visibility_kb_articles', to='core.department'),
        ),
    ]
