# Generated by Django 6.0.3 on 2026-04-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketmessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
