# Generated by Django 6.0.3 on 2026-04-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketmessage_is_internal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='is_internal',
        ),
    ]
