# Generated by Django 6.0.3 on 2026-04-27 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_is_internal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_tickets', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='is_system_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_for_branch', 'Waiting for Branch'), ('closed', 'Closed'), ('merged', 'Merged')], default='open', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticketstatushistory',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_for_branch', 'Waiting for Branch'), ('closed', 'Closed'), ('merged', 'Merged')], max_length=30),
        ),
        migrations.CreateModel(
            name='TicketMergeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('merged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('primary_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_histories_as_primary', to='tickets.ticket')),
                ('secondary_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_histories_as_secondary', to='tickets.ticket')),
            ],
            options={
                'verbose_name_plural': 'Ticket merge histories',
                'ordering': ['-merged_at'],
            },
        ),
    ]
