# Generated by Django 6.0.3 on 2026-06-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_pending_transfer_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
