# Generated by Django 6.0.3 on 2026-06-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_client_name_ticket_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='client_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client_phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
