# Generated by Django 6.0.3 on 2026-06-19 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_client_name_alter_ticket_client_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticketstatushistory',
            index=models.Index(fields=['ticket', 'created_at'], name='tickets_tic_ticket__81f633_idx'),
        ),
    ]
