# Generated by Django 6.0.3 on 2026-06-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticketstatushistory_tickets_tic_ticket__81f633_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketstatushistory',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ticketstatushistory',
            name='event_type',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('transfer_requested', 'Transfer Requested'), ('transfer_accepted', 'Transfer Accepted'), ('transfer_denied', 'Transfer Denied'), ('transfer_cancelled', 'Transfer Cancelled'), ('merged', 'Ticket Merged'), ('priority_changed', 'Priority Changed'), ('assigned', 'Assigned'), ('reopened', 'Reopened')], default='status_change', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticketstatushistory',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_for_branch', 'Waiting for Branch'), ('closed', 'Closed'), ('merged', 'Merged')], default='', max_length=30),
        ),
    ]
