# Generated by Django 6.0.3 on 2026-07-30 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_i18n_verbose_names'),
        ('tickets', '0011_ticketstatushistory_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='message_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client_name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client_phone',
            field=models.CharField(default='', max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_for_branch', 'Waiting'), ('closed', 'Closed'), ('merged', 'Merged')], default='open', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='ticketstatushistory',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_for_branch', 'Waiting'), ('closed', 'Closed'), ('merged', 'Merged')], default='', max_length=30),
        ),
    ]
