# Generated by Django 6.0.3 on 2026-09-26 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_ticket_hotpaths(apps, schema_editor):
    Ticket = apps.get_model("tickets", "Ticket")
    TicketMessage = apps.get_model("tickets", "TicketMessage")
    from django.db.models import Count
    from tickets.models import phone_digits

    for ticket in Ticket.objects.exclude(client_phone="").iterator():
        digits = phone_digits(ticket.client_phone)
        if digits != (ticket.client_phone_digits or ""):
            Ticket.objects.filter(pk=ticket.pk).update(client_phone_digits=digits)

    (
        Ticket.objects.annotate(message_count=Count("messages"))
        .filter(message_count__gt=1)
        .update(has_followup_message=True)
    )

    notice = getattr(settings, "TICKET_UNPICKED_SYSTEM_MESSAGE", "Someone will help you soon.")
    noticed_ids = list(
        TicketMessage.objects.filter(is_system_message=True, message=notice).values_list(
            "ticket_id", flat=True
        )
    )
    if noticed_ids:
        Ticket.objects.filter(pk__in=noticed_ids).update(unpicked_notice_sent=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_i18n_verbose_names'),
        ('tickets', '0012_ticketmessage_message_ar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDailyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('last_seq', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='client_phone_digits',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='has_followup_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='unpicked_notice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'is_system_message'], name='tickets_tic_ticket__103d86_idx'),
        ),
        migrations.AddField(
            model_name='ticketdailycounter',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_daily_counters', to='core.branch'),
        ),
        migrations.AddConstraint(
            model_name='ticketdailycounter',
            constraint=models.UniqueConstraint(fields=('branch', 'day'), name='uniq_branch_day_ticket_seq'),
        ),
        migrations.RunPython(backfill_ticket_hotpaths, migrations.RunPython.noop),
    ]
