# Generated by Django 6.0.3 on 2026-09-30 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_i18n_verbose_names'),
        ('tickets', '0013_performance_hotpaths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['department', '-created_at'], name='tkt_dept_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['branch', '-created_at'], name='tkt_branch_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['department', '-updated_at'], name='tkt_dept_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['branch', '-updated_at'], name='tkt_branch_updated_idx'),
        ),
    ]
