# Generated by Django 6.0.3 on 2026-07-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_inappnotification_notificatio_recipie_21a7ca_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_ticket', 'New Ticket'), ('ticket_picked', 'Ticket Picked'), ('status_change', 'Status Change'), ('message', 'Message'), ('transfer', 'Transfer'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
