# Generated by Django 6.0.3 on 2026-07-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_drop_webpush_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_ticket', 'New Ticket'), ('ticket_picked', 'Ticket Picked'), ('status_change', 'Status Change'), ('message', 'Message'), ('transfer', 'Transfer'), ('announcement', 'Announcement'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
