# Generated by Django 6.0.3 on 2026-07-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_announcement_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='message_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='title_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
