# Generated by Django 6.0.3 on 2026-07-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_inappnotification_message_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='message_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
