# Generated by Django 6.0.3 on 2026-09-26 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_drop_webpush_user_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['recipient', 'title', 'link', 'created_at'], name='notificatio_recipie_e247f4_idx'),
        ),
    ]
